package:
  name: lxml
  version: 4.9.0
source:
  sha256: 520461c36727268a989790aef08884347cd41f2d8ae855489ccf40b50321d8d7
  url: https://files.pythonhosted.org/packages/aa/23/bda4e9881090f0f5e33e2efe89aacfa0668eb6e1ab2de28591e2912d78d4/lxml-4.9.0.tar.gz
build:
  cflags: |
    -Wno-implicit-function-declaration
requirements:
  run:
    pyodide:
      - libxml
      - libxslt
    pypi:
      beautifulsoup4: "4.11.0"
      cssselect: "1.1.0"
      html5lib: "1.1"
      six: 1.16.0
      webencodings: 0.5.1
      soupsieve: 2.3.2.post1
test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
