package:
  name: pygame
  version: 2.1.3dev5
source:
  url: https://github.com/pygame/pygame/archive/cfcbda61ec357121987307590867212ca9639a63.zip
  sha256: 98f05ffa9deb6340376cd8ee3624f5657cc5c3e2e92e9b6adb438e22a801e27a
build:
  script: |
    embuilder build --pic sdl2
    embuilder build --pic sdl2_gfx
    embuilder build --pic sdl2_image
    embuilder build --pic sdl2_mixer
    embuilder build --pic sdl2_ttf
    export SDL_CONFIG=$(em-config CACHE)/sysroot/bin/sdl2-config
    export PREFIX=""
    export PYGAME_EXTRA_BASE
    export CFLAGS="-DBUILD_STATIC -DSDL_NO_COMPAT -ferror-limit=1"
    sed -i "s@sysconfig.get_config_var('MACHDEP') == 'emscripten'@True@" buildconfig/config.py

requirements:
  run:
    - numpy
test:
  imports:
    - pygame
about:
  home: https://www.pygame.org
  PyPI: https://pypi.org/project/pygame
  summary: Python Game Development
  license: LGPL
