package:
  name: libproj
  version: 8.2.1

source:
  sha256: 76ed3d0c3a348a6693dfae535e5658bbfd47f71cb7ff7eb96d9f12f7e068b1cf
  url: https://download.osgeo.org/proj/proj-8.2.1.tar.gz

requirements:
  host:
    - libtiff

build:
  sharedlibrary: true
  script: |
    mkdir -p build
    mkdir -p dist
    export DISTDIR=$(pwd)/dist

    echo "set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS TRUE)" > build/SupportSharedLib.cmake

    cd build \
        && LDFLAGS="${SIDE_MODULE_LDFLAGS} -s NODERAWFS=1 -sUSE_ZLIB=1 -sUSE_SQLITE3 -sFORCE_FILESYSTEM=1" emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=$WASM_LIBRARY_DIR \
        -DCMAKE_PROJECT_INCLUDE=$(pwd)/SupportSharedLib.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_CURL=OFF \
        -DBUILD_APPS=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_TESTING=OFF \
        -DTIFF_INCLUDE_DIR=$WASM_LIBRARY_DIR/include \
        -DTIFF_LIBRARY=$WASM_LIBRARY_DIR/lib/libtiff.a \
        -DCMAKE_C_FLAGS="-fPIC" \
        -DCMAKE_CXX_FLAGS="-fPIC"

    emmake make -j ${PYODIDE_JOBS:-3} install
    cp $WASM_LIBRARY_DIR/lib/libproj.so $DISTDIR/libproj.so
