package:
  name: pillow_heif
  version: 0.14.0
source:
  url: https://files.pythonhosted.org/packages/07/23/bc7a261401034b289a60c22015f47ad98d40d7681fd06d2cefa6e1ac2e6d/pillow_heif-0.14.0.tar.gz
  sha256: 7abd0279f0ec8b5ba1513dc586e52173666ed9278b38e219bf47da92704262cb
requirements:
  run:
    - cffi
    - Pillow
    - libheif
  host:
    - cffi
    - libheif
test:
  imports:
    - pillow_heif
about:
  home: https://github.com/bigcat88/pillow_heif
  PyPI: https://pypi.org/project/pillow_heif
  summary: Python 3.6+ interface to libheif library
  license: LGPLv2.1
# Note: this package needs to be manually upgraded to the next version
