package:
  name: libx265
  version: 1.12.0

source:
  url: https://bitbucket.org/multicoreware/x265_git/downloads/x265_3.5.tar.gz
  sha256: e70a3335cacacbba0b3a20ec6fecd6783932288ebc8163ad74bcc9606477cae8

build:
  library: true
  script: |
    emcmake cmake \
      -DCMAKE_C_FLAGS="-fPIC" \
      -DCMAKE_CXX_FLAGS="-fPIC" \
      -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
      -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$(pwd)/bin \
      -DBUILD_SHARED_LIBS=OFF \
      ./source
    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
