package:
  name: micropip
  version: "0.1"
  _tag: pyodide.stdlib
requirements:
  run:
    pyodide:
      - distutils # TODO: remove once there is a release with https://github.com/pypa/packaging/pull/396
    pypi:
      packaging: "21.3"
      pyparsing: 3.0.9
source:
  path: src
test:
  imports:
    - micropip
