package:
  name: micropip
  version: "0.1"
  _tag: pyodide.stdlib
requirements:
  run:
    - distutils # TODO: remove once there is a release with https://github.com/pypa/packaging/pull/396
  pip:
    - packaging
    - pyparsing
source:
  path: src
test:
  imports:
    - micropip
