package:
  name: lightgbm
  version: 4.1.0
source:
  url: https://files.pythonhosted.org/packages/98/a9/01f50aee85949ba713733b69a3f0b42d39719a414a0e29bdf2a9f05ecc53/lightgbm-4.1.0.tar.gz
  sha256: bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc
build:
  backend-flags: cmake.define.USE_OPENMP=OFF
  exports: whole_archive # FIXME: using "requested" fails with SIGKILL, not sure why
requirements:
  run:
    - numpy
    - scipy
    - scikit-learn
test:
  imports:
    - lightgbm
about:
  home: https://github.com/microsoft/LightGBM
  PyPI: https://pypi.org/project/lightgbm
  summary: LightGBM Python Package
  license: The MIT License (Microsoft)
