package:
  name: pyinstrument
  version: 4.6.1
  top-level:
    - pyinstrument
source:
  url: https://files.pythonhosted.org/packages/55/f5/43050b162b49d1897bf55716dd3a4ebeeb1b22a1785801a61ab3c43cabee/pyinstrument-4.6.1.tar.gz
  sha256: f4731b27121350f5a983d358d2272fe3df2f538aed058f57217eef7801a89288
about:
  home: https://github.com/joerick/pyinstrument
  PyPI: https://pypi.org/project/pyinstrument
  summary: Call stack profiler for Python. Shows you why your code is slow!
  license: BSD-3-Clause
