package:
  name: pygame-ce
  version: 2.5.3
  top-level:
    - pygame
source:
  url: https://files.pythonhosted.org/packages/source/p/pygame_ce/pygame_ce-2.5.3.tar.gz
  sha256: dc04f0bf1a270a84eb371556298a9902b9c4ab08137c9dd10ef03fa4e7fcbfed
  extras:
    - [extras/meson.build, meson.build]
    - [extras/src_c/_sdl2/meson.build, src_c/_sdl2/meson.build]
    - [extras/src_c/meson.build, src_c/meson.build]
    - [extras/src_c/static.c, src_c/static.c]
  patches:
    - patches/0001-Replace-OpenAudioDevice-with-OpenAudio.patch
    - patches/0002-freetype-init.patch
requirements:
  constraint:
    - setuptools < 75
build:
  script: |
    embuilder build sdl2 sdl2_ttf sdl2_image sdl2_mixer sdl2_gfx libjpeg libpng giflib harfbuzz vorbis mpg123 libmodplug freetype libhtml5 --pic

    # Build sdl2_mixer with formats enabled.
    # this is a workaround until https://github.com/emscripten-core/emscripten/pull/24158 is merged and released
    # We build both libSDL2_mixer.a and libSDL2_mixer.a with different formats here,
    # because meson will detect find the file "libSDL2_mixer.a" while emscripten puts formats in the name.
    touch temp.c
    emcc temp.c -fPIC -sRELOCATABLE=1 -sUSE_SDL_MIXER=2 -sSDL2_MIXER_FORMATS=
    emcc temp.c -fPIC -sRELOCATABLE=1 -sUSE_SDL_MIXER=2 -sSDL2_MIXER_FORMATS=mid,mod,mp3,ogg
    export SDL_CONFIG=$(em-config CACHE)/sysroot/bin/sdl2-config
  backend-flags: |
    setup-args=-Dmidi=disabled build-dir=build
  cflags: |
    -sRELOCATABLE=1
    -DSDL_NO_COMPAT
    -DBUILD_STATIC
    -ferror-limit=1
    -sUSE_SDL=2
    -sUSE_SDL_MIXER=2
    -sSDL2_MIXER_FORMATS=mid,mod,mp3,ogg
    -sUSE_SDL_TTF=2
    -sUSE_SDL_IMAGE=2
    -sSDL2_IMAGE_FORMATS=bmp,gif,jpg,png
    -sUSE_SDL_GFX=2
    -sUSE_FREETYPE=1
    -sUSE_LIBJPEG=1
    -sUSE_LIBPNG=1
    -sUSE_GIFLIB=1
    -sUSE_HARFBUZZ=1
    -Wno-unreachable-code-fallthrough
  ldflags: |
    -sRELOCATABLE=1
    -sUSE_SDL=2
    -sUSE_SDL_MIXER=2
    -sSDL2_MIXER_FORMATS=mid,mod,mp3,ogg
    -sUSE_SDL_TTF=2
    -sUSE_SDL_IMAGE=2
    -sSDL2_IMAGE_FORMATS=bmp,gif,jpg,png
    -sUSE_SDL_GFX=2
    -sUSE_FREETYPE=1
    -sUSE_LIBJPEG=1
    -sUSE_LIBPNG=1
    -sUSE_GIFLIB=1
    -sUSE_HARFBUZZ=1
  post: |
    # Remove docs to reduce the size of a wheel
    # (Perhaps also remove typeshed and examples too?)
    rm -rf ./pygame/docs

    # WASM version of pygame uses a single module 'pygame_static',
    # and pygame_static calls PyInit_* functions from other modules.
    # This is okay when all these modules are bundled in a single module: libpython.
    # But as we don't do that, we need to load these modules globally, so that
    # pygame_static can see the symbols.
    STATIC_OBJS=$(find ${PKG_BUILD_DIR}/build -name "*.o")
    echo "build dir: " $PKG_BUILD_DIR
    echo "static objs: " $STATIC_OBJS

    SHARED_LIBS=$(find ${WHEELDIR} -name "*.so" ! -name "static*.so")
    echo "shared libs: " $SHARED_LIBS

    emcc \
      -shared \
      ${SIDE_MODULE_LDFLAGS} \
      -fPIC \
      -lSDL2 \
      -lSDL2_image-bmp-gif-jpg-png-wasm-sjlj \
      -lSDL2_ttf \
      -lSDL2_mixer-mid-mod-mp3-ogg \
      -lSDL2_gfx \
      -lfreetype-legacysjlj \
      -lharfbuzz \
      -lpng-legacysjlj \
      -ljpeg \
      -lgif \
      -lvorbis \
      -lmodplug \
      -lmpg123 \
      -logg \
      -lhtml5 \
      ${STATIC_OBJS} \
      ${SHARED_LIBS} \
      -sSUPPORT_LONGJMP=wasm \
      -o pygame_static.so

    # Remove duplicated static.so module
    rm -f ./pygame/static*.so
about:
  home: https://www.pygame.org
  PyPI: https://pypi.org/project/pygame
  summary: Python Game Development
  license: LGPL-2.1
