# XGBoost dropped support for 32-bit system, so we can't update more recent versions
# See: https://github.com/dmlc/xgboost/issues/9035
package:
  name: xgboost
  version: 1.6.2
  top-level:
    - xgboost
source:
  url: https://files.pythonhosted.org/packages/25/e0/f00261d3357eafbe7c657de718abd3c0f6613633a38d05350f63ee099cde/xgboost-1.6.2.tar.gz
  sha256: e1f5c91ba88cf8edb409d7fd2ca150dcd80b6f2115587d87365f0c10b2d4f009
  patches:
    - patches/0003-Fix-type-mismatch-for-CSR-conversion-in-c_api.patch
build:
  cflags: |
    -DDMLC_USE_FOPEN64=0
    -DDMLC_ENABLE_STD_THREAD=0
    -DDMLC_CXX11_THREAD_LOCAL=0
    -DUSE_OPENMP=0
  exports: requested
requirements:
  run:
    - numpy
    - scipy
    - setuptools
about:
  home: https://github.com/dmlc/xgboost
  PyPI: https://pypi.org/project/xgboost
  summary: XGBoost Python Package
  license: Apache-2.0
