package:
  name: libheif
  version: 1.17.5
  tag:
    - library
source:
  url: https://github.com/strukturag/libheif/releases/download/v1.17.5/libheif-1.17.5.tar.gz
  sha256: 38ab01938ef419dbebb98346dc0b1c8bb503a0449ea61a0e409a988786c2af5b

requirements:
  host:
    - libde265

build:
  type: shared_library
  script: |
    # Build options are adapted from https://github.com/strukturag/libheif/blob/v1.12.0/build-emscripten.sh
    # heif_emscripten.h is for building js APIs, but we don't want them.
    sed -i 's@#include "heif_emscripten.h"@@' libheif/heif.cc
    emcmake cmake \
      -DCMAKE_CXX_FLAGS="-fPIC" \
      -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
      -DENABLE_MULTITHREADING_SUPPORT=OFF \
      -DWITH_GDK_PIXBUF=OFF \
      -DWITH_EXAMPLES=OFF \
      -DENABLE_PLUGIN_LOADING=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DBUILD_TESTING=OFF \
      -DLIBDE265_INCLUDE_DIR=${WASM_LIBRARY_DIR}/include \
      -DLIBDE265_LIBRARY=${WASM_LIBRARY_DIR}/lib/libde265.a \
      ./

    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
    cp ${WASM_LIBRARY_DIR}/lib/libheif.so ${DISTDIR}
