package:
  name: numpy
  version: 2.1.3
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  url: https://files.pythonhosted.org/packages/25/ca/1166b75c21abd1da445b97bf1fa2f14f423c6cfb4fc7c4ef31dccf9f6a94/numpy-2.1.3.tar.gz
  sha256: aa08e04e08aaf974d4458def539dece0d28146d866a39da5639596f4921fd761

build:
  # numpy uses vendored meson, so we need to pass the cross file manually
  backend-flags: |
    setup-args=-Dallow-noblas=true
    setup-args=--cross-file=${MESON_CROSS_FILE}
  # numpy creates numpy/distutils/__pycache__ directory during the build.
  # It breaks our test because there is a .pyc in the directory.
  post: |
    rm -rf numpy/distutils/__pycache__
  # NumPy 2.1 disabled visibility for symbols outside of extension modules
  # by default, so this breaks SciPy tests from modules that use f2py to
  # build because they rely on the visibility of symbols in NumPy. This flag
  # is currently used as a stop-gap measure. For more information, please see
  # 1. https://github.com/numpy/numpy/pull/26286, and
  # 2. https://github.com/numpy/numpy/pull/26103.
  cflags: |
    -Wno-return-type
  cross-build-env: true
  cross-build-files:
    - numpy/_core/include/numpy/numpyconfig.h
    - numpy/_core/include/numpy/_numpyconfig.h
    - numpy/_core/lib/libnpymath.a
    - numpy/random/lib/libnpyrandom.a
about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - agriyakhetarpal
