package:
  name: numpy
  version: 1.23.0
  top-level:
    - numpy
source:
  url: https://files.pythonhosted.org/packages/f6/d8/ab692a75f584d13c6542c3994f75def5bce52ded9399f52e230fe402819d/numpy-1.22.4.zip
  sha256: 425b390e4619f58d8526b3dcf656dde069133ae5c240229821f01b5f44ea07af

  patches:
    - patches/0001-ENH-Add-support-for-platforms-with-missing-fenv-flag.patch
    - patches/0002-ENH-cross-compilation-use-sysconfig-to-determine-if-.patch
    - patches/0003-ENH-Fix-pointer-size-determination-for-cross-build.patch
requirements:
  host:
    - CLAPACK
    - CBLAS
    - blis
  run:
    # - CLAPACK
    # - CBLAS  # netlib blas
    - blis # blis
build:
  backend-flags: --disable-optimization
  cflags: |
    -Wno-return-type
  cross-build-env: true
  cross-build-files:
    - numpy/core/include/numpy/numpyconfig.h
    - numpy/core/include/numpy/_numpyconfig.h
    - numpy/core/lib/libnpymath.a
    - numpy/random/lib/libnpyrandom.a
  script: |
    echo "[blis]" >> site.cfg
    echo "libraries = blis" >> site.cfg
    echo "library_dirs = ${WASM_LIBRARY_DIR}/lib" >> site.cfg
    echo "include_dirs = ${WASM_LIBRARY_DIR}/include/blis" >> site.cfg

    # blis
    export BLAS="blis"
    export LDFLAGS="-L${WASM_LIBRARY_DIR}/lib"

    # export NPY_BLAS_LIBS="-I$WASM_LIBRARY_DIR/include -L$WASM_LIBRARY_DIR/lib -lblis"
    # blas (netlib blas)
    # export NPY_BLAS_LIBS="-I$WASM_LIBRARY_DIR/include -L$WASM_LIBRARY_DIR/lib -lblas"

    # export NPY_LAPACK_LIBS="-I$WASM_LIBRARY_DIR/include -L$WASM_LIBRARY_DIR/lib -llapack"
about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD
