name: main

on: [push]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.2

      - name: Install requirements
        shell: bash -l {0}
        run: |
          mkdir test-results
          cd pyodide-build && python3 -m pip install -e ".[test]" && cd ..
          python3 -m pip install pytest-cov hypothesis pytz
      - name: Run tests
        shell: bash -l {0}
        run: |
          PYODIDE_ROOT=. pytest \
              --junitxml=test-results/junit.xml \
              --verbose \
              --runtime=host \
              --cov=pyodide_build --cov=pyodide \
              src pyodide-build packages/micropip/ packages/_tests
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

  build-core:
    uses: ./.github/workflows/build.yml
    with:
      packages: core
      artifacts-prefix-prev: ""
      artifacts-prefix: core
      retention-days: 30

  build-no-numpy-dependents:
    needs: [build-core]
    uses: ./.github/workflows/build.yml
    with:
      packages: no-numpy-dependents
      artifacts-prefix-prev: core
      artifacts-prefix: no-numpy-dependents
      retention-days: 30

  build-packages:
    needs: [build-no-numpy-dependents]
    uses: ./.github/workflows/build.yml
    with:
      packages: "*"
      artifacts-prefix-prev: no-numpy-dependents
      artifacts-prefix: packages
      retention-days: 30

  test-core:
    needs: [build-core]
    uses: ./.github/workflows/test.yml
    with:
      test-params: -k "not webworker" src packages/micropip  packages/fpcast-test packages/sharedlib-test-py/ packages/cpp-exceptions-test/
      artifacts-prefix-build: core
